{
	"patcher": {
		"fileversion": 1,
		"appversion": { "major": 8, "minor": 5, "revision": 0, "architecture": "x64", "modernui": 1 },
		"classnamespace": "box",
		"rect": [ 100.0, 100.0, 1200.0, 700.0 ],
		"bglocked": 0,
		"openinpresentation": 0,
		"default_fontsize": 12.0,
		"default_fontface": 0,
		"default_fontname": "Arial",
		"gridonopen": 1,
		"gridsize": [ 15.0, 15.0 ],
		"gridsnaponopen": 1,
		"objectsnaponopen": 1,
		"statusbarvisible": 2,
		"toolbarvisible": 1,
		"boxes": [
			{ "box": { "id": "obj-100", "maxclass": "comment", "text": "AbletonMCP Tap v1 — audio ears for the bridge. Serves levels on 127.0.0.1:9878. Build steps: m4l/README-lab.md", "numinlets": 1, "numoutlets": 0, "patching_rect": [ 20.0, 10.0, 640.0, 20.0 ] } },
			{ "box": { "id": "obj-1", "maxclass": "newobj", "text": "plugin~", "numinlets": 2, "numoutlets": 2, "outlettype": [ "signal", "signal" ], "patching_rect": [ 20.0, 50.0, 60.0, 22.0 ] } },
			{ "box": { "id": "obj-2", "maxclass": "newobj", "text": "plugout~", "numinlets": 2, "numoutlets": 2, "outlettype": [ "signal", "signal" ], "patching_rect": [ 20.0, 620.0, 66.0, 22.0 ] } },
			{ "box": { "id": "obj-3", "maxclass": "newobj", "text": "+~", "numinlets": 2, "numoutlets": 1, "outlettype": [ "signal" ], "patching_rect": [ 160.0, 110.0, 34.0, 22.0 ] } },
			{ "box": { "id": "obj-4", "maxclass": "newobj", "text": "*~ 0.5", "numinlets": 2, "numoutlets": 1, "outlettype": [ "signal" ], "patching_rect": [ 160.0, 145.0, 44.0, 22.0 ] } },
			{ "box": { "id": "obj-5", "maxclass": "newobj", "text": "fffb~ 8 60. 2. 5.", "numinlets": 1, "numoutlets": 8, "outlettype": [ "signal", "signal", "signal", "signal", "signal", "signal", "signal", "signal" ], "patching_rect": [ 160.0, 185.0, 110.0, 22.0 ] } },

			{ "box": { "id": "obj-b0", "maxclass": "newobj", "text": "average~ 1000 rms", "numinlets": 1, "numoutlets": 1, "outlettype": [ "signal" ], "patching_rect": [ 40.0, 260.0, 115.0, 22.0 ] } },
			{ "box": { "id": "obj-s0", "maxclass": "newobj", "text": "snapshot~ 100", "numinlets": 1, "numoutlets": 1, "outlettype": [ "float" ], "patching_rect": [ 40.0, 295.0, 90.0, 22.0 ] } },
			{ "box": { "id": "obj-m0", "maxclass": "message", "text": "band 0 \\$1", "numinlets": 2, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 40.0, 330.0, 80.0, 22.0 ] } },
			{ "box": { "id": "obj-b1", "maxclass": "newobj", "text": "average~ 1000 rms", "numinlets": 1, "numoutlets": 1, "outlettype": [ "signal" ], "patching_rect": [ 175.0, 260.0, 115.0, 22.0 ] } },
			{ "box": { "id": "obj-s1", "maxclass": "newobj", "text": "snapshot~ 100", "numinlets": 1, "numoutlets": 1, "outlettype": [ "float" ], "patching_rect": [ 175.0, 295.0, 90.0, 22.0 ] } },
			{ "box": { "id": "obj-m1", "maxclass": "message", "text": "band 1 \\$1", "numinlets": 2, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 175.0, 330.0, 80.0, 22.0 ] } },
			{ "box": { "id": "obj-b2", "maxclass": "newobj", "text": "average~ 1000 rms", "numinlets": 1, "numoutlets": 1, "outlettype": [ "signal" ], "patching_rect": [ 310.0, 260.0, 115.0, 22.0 ] } },
			{ "box": { "id": "obj-s2", "maxclass": "newobj", "text": "snapshot~ 100", "numinlets": 1, "numoutlets": 1, "outlettype": [ "float" ], "patching_rect": [ 310.0, 295.0, 90.0, 22.0 ] } },
			{ "box": { "id": "obj-m2", "maxclass": "message", "text": "band 2 \\$1", "numinlets": 2, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 310.0, 330.0, 80.0, 22.0 ] } },
			{ "box": { "id": "obj-b3", "maxclass": "newobj", "text": "average~ 1000 rms", "numinlets": 1, "numoutlets": 1, "outlettype": [ "signal" ], "patching_rect": [ 445.0, 260.0, 115.0, 22.0 ] } },
			{ "box": { "id": "obj-s3", "maxclass": "newobj", "text": "snapshot~ 100", "numinlets": 1, "numoutlets": 1, "outlettype": [ "float" ], "patching_rect": [ 445.0, 295.0, 90.0, 22.0 ] } },
			{ "box": { "id": "obj-m3", "maxclass": "message", "text": "band 3 \\$1", "numinlets": 2, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 445.0, 330.0, 80.0, 22.0 ] } },
			{ "box": { "id": "obj-b4", "maxclass": "newobj", "text": "average~ 1000 rms", "numinlets": 1, "numoutlets": 1, "outlettype": [ "signal" ], "patching_rect": [ 580.0, 260.0, 115.0, 22.0 ] } },
			{ "box": { "id": "obj-s4", "maxclass": "newobj", "text": "snapshot~ 100", "numinlets": 1, "numoutlets": 1, "outlettype": [ "float" ], "patching_rect": [ 580.0, 295.0, 90.0, 22.0 ] } },
			{ "box": { "id": "obj-m4", "maxclass": "message", "text": "band 4 \\$1", "numinlets": 2, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 580.0, 330.0, 80.0, 22.0 ] } },
			{ "box": { "id": "obj-b5", "maxclass": "newobj", "text": "average~ 1000 rms", "numinlets": 1, "numoutlets": 1, "outlettype": [ "signal" ], "patching_rect": [ 715.0, 260.0, 115.0, 22.0 ] } },
			{ "box": { "id": "obj-s5", "maxclass": "newobj", "text": "snapshot~ 100", "numinlets": 1, "numoutlets": 1, "outlettype": [ "float" ], "patching_rect": [ 715.0, 295.0, 90.0, 22.0 ] } },
			{ "box": { "id": "obj-m5", "maxclass": "message", "text": "band 5 \\$1", "numinlets": 2, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 715.0, 330.0, 80.0, 22.0 ] } },
			{ "box": { "id": "obj-b6", "maxclass": "newobj", "text": "average~ 1000 rms", "numinlets": 1, "numoutlets": 1, "outlettype": [ "signal" ], "patching_rect": [ 850.0, 260.0, 115.0, 22.0 ] } },
			{ "box": { "id": "obj-s6", "maxclass": "newobj", "text": "snapshot~ 100", "numinlets": 1, "numoutlets": 1, "outlettype": [ "float" ], "patching_rect": [ 850.0, 295.0, 90.0, 22.0 ] } },
			{ "box": { "id": "obj-m6", "maxclass": "message", "text": "band 6 \\$1", "numinlets": 2, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 850.0, 330.0, 80.0, 22.0 ] } },
			{ "box": { "id": "obj-b7", "maxclass": "newobj", "text": "average~ 1000 rms", "numinlets": 1, "numoutlets": 1, "outlettype": [ "signal" ], "patching_rect": [ 985.0, 260.0, 115.0, 22.0 ] } },
			{ "box": { "id": "obj-s7", "maxclass": "newobj", "text": "snapshot~ 100", "numinlets": 1, "numoutlets": 1, "outlettype": [ "float" ], "patching_rect": [ 985.0, 295.0, 90.0, 22.0 ] } },
			{ "box": { "id": "obj-m7", "maxclass": "message", "text": "band 7 \\$1", "numinlets": 2, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 985.0, 330.0, 80.0, 22.0 ] } },

			{ "box": { "id": "obj-6", "maxclass": "newobj", "text": "average~ 1000 rms", "numinlets": 1, "numoutlets": 1, "outlettype": [ "signal" ], "patching_rect": [ 300.0, 110.0, 115.0, 22.0 ] } },
			{ "box": { "id": "obj-7", "maxclass": "newobj", "text": "snapshot~ 100", "numinlets": 1, "numoutlets": 1, "outlettype": [ "float" ], "patching_rect": [ 300.0, 145.0, 90.0, 22.0 ] } },
			{ "box": { "id": "obj-8", "maxclass": "message", "text": "rms \\$1", "numinlets": 2, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 300.0, 180.0, 60.0, 22.0 ] } },

			{ "box": { "id": "obj-9", "maxclass": "newobj", "text": "peakamp~ 100", "numinlets": 1, "numoutlets": 1, "outlettype": [ "float" ], "patching_rect": [ 450.0, 110.0, 90.0, 22.0 ] } },
			{ "box": { "id": "obj-10", "maxclass": "message", "text": "peak 0 \\$1", "numinlets": 2, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 450.0, 145.0, 76.0, 22.0 ] } },
			{ "box": { "id": "obj-11", "maxclass": "newobj", "text": "peakamp~ 100", "numinlets": 1, "numoutlets": 1, "outlettype": [ "float" ], "patching_rect": [ 560.0, 110.0, 90.0, 22.0 ] } },
			{ "box": { "id": "obj-12", "maxclass": "message", "text": "peak 1 \\$1", "numinlets": 2, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 560.0, 145.0, 76.0, 22.0 ] } },

			{ "box": { "id": "obj-20", "maxclass": "newobj", "text": "node.script tap_server.js @autostart 1 @watch 0", "numinlets": 1, "numoutlets": 2, "outlettype": [ "", "" ], "patching_rect": [ 300.0, 470.0, 290.0, 22.0 ] } },
			{ "box": { "id": "obj-21", "maxclass": "newobj", "text": "route status", "numinlets": 1, "numoutlets": 2, "outlettype": [ "", "" ], "patching_rect": [ 300.0, 510.0, 76.0, 22.0 ] } },
			{ "box": { "id": "obj-22", "maxclass": "newobj", "text": "prepend set", "numinlets": 1, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 300.0, 545.0, 74.0, 22.0 ] } },
			{ "box": { "id": "obj-23", "maxclass": "message", "text": "STARTING", "numinlets": 2, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 300.0, 580.0, 120.0, 22.0 ] } }
		],
		"lines": [
			{ "patchline": { "source": [ "obj-1", 0 ], "destination": [ "obj-2", 0 ] } },
			{ "patchline": { "source": [ "obj-1", 1 ], "destination": [ "obj-2", 1 ] } },
			{ "patchline": { "source": [ "obj-1", 0 ], "destination": [ "obj-3", 0 ] } },
			{ "patchline": { "source": [ "obj-1", 1 ], "destination": [ "obj-3", 1 ] } },
			{ "patchline": { "source": [ "obj-3", 0 ], "destination": [ "obj-4", 0 ] } },
			{ "patchline": { "source": [ "obj-4", 0 ], "destination": [ "obj-5", 0 ] } },
			{ "patchline": { "source": [ "obj-4", 0 ], "destination": [ "obj-6", 0 ] } },
			{ "patchline": { "source": [ "obj-6", 0 ], "destination": [ "obj-7", 0 ] } },
			{ "patchline": { "source": [ "obj-7", 0 ], "destination": [ "obj-8", 0 ] } },
			{ "patchline": { "source": [ "obj-1", 0 ], "destination": [ "obj-9", 0 ] } },
			{ "patchline": { "source": [ "obj-9", 0 ], "destination": [ "obj-10", 0 ] } },
			{ "patchline": { "source": [ "obj-1", 1 ], "destination": [ "obj-11", 0 ] } },
			{ "patchline": { "source": [ "obj-11", 0 ], "destination": [ "obj-12", 0 ] } },
			{ "patchline": { "source": [ "obj-5", 0 ], "destination": [ "obj-b0", 0 ] } },
			{ "patchline": { "source": [ "obj-5", 1 ], "destination": [ "obj-b1", 0 ] } },
			{ "patchline": { "source": [ "obj-5", 2 ], "destination": [ "obj-b2", 0 ] } },
			{ "patchline": { "source": [ "obj-5", 3 ], "destination": [ "obj-b3", 0 ] } },
			{ "patchline": { "source": [ "obj-5", 4 ], "destination": [ "obj-b4", 0 ] } },
			{ "patchline": { "source": [ "obj-5", 5 ], "destination": [ "obj-b5", 0 ] } },
			{ "patchline": { "source": [ "obj-5", 6 ], "destination": [ "obj-b6", 0 ] } },
			{ "patchline": { "source": [ "obj-5", 7 ], "destination": [ "obj-b7", 0 ] } },
			{ "patchline": { "source": [ "obj-b0", 0 ], "destination": [ "obj-s0", 0 ] } },
			{ "patchline": { "source": [ "obj-b1", 0 ], "destination": [ "obj-s1", 0 ] } },
			{ "patchline": { "source": [ "obj-b2", 0 ], "destination": [ "obj-s2", 0 ] } },
			{ "patchline": { "source": [ "obj-b3", 0 ], "destination": [ "obj-s3", 0 ] } },
			{ "patchline": { "source": [ "obj-b4", 0 ], "destination": [ "obj-s4", 0 ] } },
			{ "patchline": { "source": [ "obj-b5", 0 ], "destination": [ "obj-s5", 0 ] } },
			{ "patchline": { "source": [ "obj-b6", 0 ], "destination": [ "obj-s6", 0 ] } },
			{ "patchline": { "source": [ "obj-b7", 0 ], "destination": [ "obj-s7", 0 ] } },
			{ "patchline": { "source": [ "obj-s0", 0 ], "destination": [ "obj-m0", 0 ] } },
			{ "patchline": { "source": [ "obj-s1", 0 ], "destination": [ "obj-m1", 0 ] } },
			{ "patchline": { "source": [ "obj-s2", 0 ], "destination": [ "obj-m2", 0 ] } },
			{ "patchline": { "source": [ "obj-s3", 0 ], "destination": [ "obj-m3", 0 ] } },
			{ "patchline": { "source": [ "obj-s4", 0 ], "destination": [ "obj-m4", 0 ] } },
			{ "patchline": { "source": [ "obj-s5", 0 ], "destination": [ "obj-m5", 0 ] } },
			{ "patchline": { "source": [ "obj-s6", 0 ], "destination": [ "obj-m6", 0 ] } },
			{ "patchline": { "source": [ "obj-s7", 0 ], "destination": [ "obj-m7", 0 ] } },
			{ "patchline": { "source": [ "obj-m0", 0 ], "destination": [ "obj-20", 0 ] } },
			{ "patchline": { "source": [ "obj-m1", 0 ], "destination": [ "obj-20", 0 ] } },
			{ "patchline": { "source": [ "obj-m2", 0 ], "destination": [ "obj-20", 0 ] } },
			{ "patchline": { "source": [ "obj-m3", 0 ], "destination": [ "obj-20", 0 ] } },
			{ "patchline": { "source": [ "obj-m4", 0 ], "destination": [ "obj-20", 0 ] } },
			{ "patchline": { "source": [ "obj-m5", 0 ], "destination": [ "obj-20", 0 ] } },
			{ "patchline": { "source": [ "obj-m6", 0 ], "destination": [ "obj-20", 0 ] } },
			{ "patchline": { "source": [ "obj-m7", 0 ], "destination": [ "obj-20", 0 ] } },
			{ "patchline": { "source": [ "obj-8", 0 ], "destination": [ "obj-20", 0 ] } },
			{ "patchline": { "source": [ "obj-10", 0 ], "destination": [ "obj-20", 0 ] } },
			{ "patchline": { "source": [ "obj-12", 0 ], "destination": [ "obj-20", 0 ] } },
			{ "patchline": { "source": [ "obj-20", 0 ], "destination": [ "obj-21", 0 ] } },
			{ "patchline": { "source": [ "obj-21", 0 ], "destination": [ "obj-22", 0 ] } },
			{ "patchline": { "source": [ "obj-22", 0 ], "destination": [ "obj-23", 1 ] } }
		]
	}
}
